INSERT INTO users (email, password, name, role) VALUES ('admin@canteen.com', 'admin123', 'Admin', 'ADMIN');
INSERT INTO users (email, password, name, role) VALUES ('faculty@canteen.com', 'fac123', 'Faculty One', 'FACULTY');
INSERT INTO users (email, password, name, role) VALUES ('student@canteen.com', 'stud123', 'Student One', 'STUDENT');

-- Menu Items with Images
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Masala Dosa', 'tiffin', 40.0, true, '/images/masala-dosa.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Uttapam', 'tiffin', 40.0, true, '/images/uttapam.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Rice', 'meals', 30.0, true, '/images/rice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Sambar', 'meals', 20.0, true, '/images/sambar.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Rasam', 'meals', 20.0, true, '/images/rasam.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Gobi Manchurian', 'chinese', 70.0, true, '/images/gobi-manchurian.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Chicken Curry', 'non-veg', 90.0, true, '/images/chicken curry.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Coffee', 'beverages', 10.0, true, '/images/coffee.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Pineapple Juice', 'beverages', 25.0, true, '/images/pinaple juice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Buttermilk', 'beverages', 10.0, true, '/images/buttermilk.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Egg Dosa', 'tiffin', 50.0, true, '/images/Egg Dosa.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Bread Omelette', 'tiffin', 40.0, true, '/images/Bread Omelette.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Pappu', 'meals', 30.0, true, '/images/pappu.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Lemon Rice', 'meals', 30.0, true, '/images/Lemon Rice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Curd Rice', 'meals', 30.0, true, '/images/Curd Rice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Tomato Rice', 'meals', 35.0, true, '/images/Tomato Rice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Veg Pulao', 'meals', 50.0, true, '/images/Veg Pulao.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Egg Fried Rice', 'chinese', 70.0, true, '/images/Egg Fried Rice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Paneer Fried Rice', 'chinese', 80.0, true, '/images/Paneer Fried Rice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Veg Noodles', 'chinese', 55.0, true, '/images/noodles.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Noodles', 'chinese', 60.0, true, '/images/noodles.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Fried Rice', 'veg', 70.0, true, '/images/Fried Rice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Samosa', 'snacks', 15.0, true, '/images/Samosa.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Mirchi Bajji', 'snacks', 15.0, true, '/images/Mirchi Bajji.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Veg Puff', 'snacks', 20.0, true, '/images/Veg Puff.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Egg Puff', 'snacks', 25.0, true, '/images/Egg Puff.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Veg Sandwich', 'snacks', 35.0, true, '/images/Veg Sandwich.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Egg Sandwich', 'snacks', 40.0, true, '/images/Egg Sandwich.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Mango Juice', 'beverages', 25.0, true, '/images/Mango Juice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Watermelon Juice', 'beverages', 25.0, true, '/images/Watermelon Juice.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Badam Milk', 'beverages', 25.0, true, '/images/Badam Milk.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Lemon Juice', 'beverages', 15.0, true, '/images/idly.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Lassi', 'beverages', 20.0, true, '/images/Lassi.jpg');
INSERT INTO menu_items (food_name, category, price, Available, image) VALUES ('Tea', 'beverages', 10.0, true, '/images/coffee.jpg');
